[project]
name = "simple-webserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "ruff>=0.11.11",
    "sqlmodel>=0.0.24",
    "uvicorn>=0.34.2",
]
